### ISSUE TITLE
Any plans to create one similar to https://github.com/atom/one-dark-syntax ?

### ISSUE THREAD

**Issue by AvinashChowdary** [sectasy0/fleet_one_dark#2]
Thanks for creating this, it so close to what I actually use in Intellij. I use https://github.com/atom/one-dark-syntax and would love if you can "port" this or provide guidance on how to do it.

**Comment by sectasy0** [comment]
Hello, I do not know if this is possible in the current stage of development of this IDE. I tried to play around in many ways with the settings, but it didn't really work out the way I wanted, if you have time you can play around with different settings and throw in a Pull Request. I tried very hard to make this style resemble as much as possible what is in the original. I will try to do it again, maybe after those updates something changes.

**Comment by sectasy0** [comment]
@AvinashChowdary 

I have improved the coloring for the `.css` files, also added more examples from other languages, and improved the current colors. It seems to me that at this point I am not able to do it better
